DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS task;

CREATE TABLE user (
    userID INTEGER PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE note (
    noteID INTEGER PRIMARY KEY,
    authorID INTEGER NOT NULL,
    isPrivate INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (authorID) REFERENCES user (userID)
);

CREATE TABLE task (
    taskID INTEGER PRIMARY KEY,
    authorID INTEGER NOT NULL,
    isPrivate INTEGER NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dueDate DATE NOT NULL DEFAULT CURRENT_DATE,
    todo TEXT NOT NULL,
    FOREIGN KEY (authorID) REFERENCES user (userID)
);